print("Hello,")
print("World!")
print("mensagem 1")
print("mensagem 2")
print("mensagem 3")
print("mensagem 4")
print("mensagem 5")
print("mensagem 6")
print("mensagem 7")
print("mensagem 8")
print("mensagem 9")
print("mensagem 10")
print("mensagem 11")
print("mensagem 12")
print("mensagem 13")
print()