text=input("Digite algo: ")
print("O tipo primitivo é ",type(text))
print("é um número? ",text.isnumeric())
print("é uma letra? ",text.isalpha())
print("é só ponto? ",text.isascii())
print("é letras/números? ",text.isalnum())
print("é só espaço? ",text.isspace())
print("é só maiuscula? ",text.isupper())
print("é só minuscula? ",text.islower())